name: render-latex
description: Renders a LaTeX file with XeLaTeX
author: James Shaw <penguinoneshaw@gmail.com>
inputs:
  root-file:
    required: true
    description: The root .tex file
  extra-packages:
    description: A file containing a list of extra packages to be included
    default: extra-packages.txt

outputs:
  output-dir:
    description: The directory the latexmk output is directed to
runs:
  using: docker
  image: "Dockerfile"
  entrypoint: /entrypoint.sh
  args:
    - "${{ inputs.root-file }}"
  env:
    EXTRA_PACKAGES_FILE: "${{ inputs.extra-packages }}"
