name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches-ignore:
      - main

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            --standalone
            --output=example.tex
            --from=markdown+smart
            --to=latex
            README.md
      - run: |
          echo "newpx" > "extra-packages.txt"

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          root-file: example

      - uses: actions/upload-artifact@v3
        with:
          name: final-document
          path: "${{ steps.test-action.outputs.output-dir }}/*.pdf"
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
          retention-days: 1
